-- Jordan XC Clinic — all migrations, in order.
-- Generated by scripts/bundle-migrations.sh on 2026-10-05. Do not edit.
-- Paste into the Supabase SQL editor and run once, on a new project.

-- ============================================================
-- 0001_initial_schema.sql
-- ============================================================
-- Jordan XC Clinic — initial schema
-- Roles, athletes/guardians, schedule, attendance, content, training plans.
-- Registration, payment, and the waiver live on the website, not here.

create type app_role as enum ('admin', 'coach', 'athlete', 'private_client', 'parent');
create type practice_status as enum ('scheduled', 'moved', 'cancelled');
create type attendance_status as enum ('present', 'absent', 'excused');
create type audience as enum ('everyone', 'clinic', 'private', 'coaches');

create table profiles (
  id uuid primary key references auth.users on delete cascade,
  full_name text not null,
  role app_role not null default 'athlete',
  date_of_birth date,
  phone text,
  graduation_year int,
  created_at timestamptz not null default now()
);

-- Lets a parent see their own athlete's schedule, training, and attendance.
create table guardian_links (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references profiles on delete cascade,
  guardian_id uuid not null references profiles on delete cascade,
  relationship text,
  created_at timestamptz not null default now(),
  unique (athlete_id, guardian_id)
);

create table practices (
  id uuid primary key default gen_random_uuid(),
  starts_at timestamptz not null,
  ends_at timestamptz,
  location_name text not null,
  meeting_point text,
  notes text,
  status practice_status not null default 'scheduled',
  audience audience not null default 'clinic',
  created_by uuid not null references profiles on delete restrict,
  created_at timestamptz not null default now()
);

create table attendance (
  id uuid primary key default gen_random_uuid(),
  practice_id uuid not null references practices on delete cascade,
  athlete_id uuid not null references profiles on delete cascade,
  status attendance_status not null,
  recorded_by uuid not null references profiles on delete restrict,
  recorded_at timestamptz not null default now(),
  unique (practice_id, athlete_id)
);

create table announcements (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references profiles on delete restrict,
  title text not null,
  body text not null,
  audience audience not null default 'everyone',
  published_at timestamptz,
  created_at timestamptz not null default now()
);

-- Educational content: articles and videos on training, nutrition, injury prevention.
create table posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references profiles on delete restrict,
  title text not null,
  slug text not null unique,
  summary text,
  body text not null,
  category text,
  hero_image_url text,
  video_url text,
  audience audience not null default 'everyone',
  published_at timestamptz,
  created_at timestamptz not null default now()
);

create table training_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  audience audience not null default 'clinic',
  created_by uuid not null references profiles on delete restrict,
  created_at timestamptz not null default now()
);

create table workouts (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references training_plans on delete cascade,
  week_number int not null,
  day_of_week int not null check (day_of_week between 1 and 7),
  title text not null,
  description text,
  distance_miles numeric(5,2),
  intensity text,
  unique (plan_id, week_number, day_of_week)
);

create table plan_assignments (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references training_plans on delete cascade,
  athlete_id uuid not null references profiles on delete cascade,
  starts_on date not null,
  assigned_by uuid not null references profiles on delete restrict,
  unique (plan_id, athlete_id)
);

create table workout_logs (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references profiles on delete cascade,
  workout_id uuid references workouts on delete set null,
  logged_on date not null,
  distance_miles numeric(5,2),
  duration_seconds int,
  effort int check (effort between 1 and 10),
  notes text,
  created_at timestamptz not null default now()
);

create index on practices (starts_at);
create index on attendance (athlete_id);
create index on plan_assignments (athlete_id);
create index on workout_logs (athlete_id, logged_on desc);

create or replace function is_coach(uid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = uid and role in ('admin', 'coach'));
$$;

-- Guardians read their own athlete's records; coaches read everything.
create or replace function can_view_athlete(uid uuid, athlete uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select uid = athlete
      or is_coach(uid)
      or exists (select 1 from guardian_links
                 where athlete_id = athlete and guardian_id = uid);
$$;

alter table profiles enable row level security;
alter table guardian_links enable row level security;
alter table practices enable row level security;
alter table attendance enable row level security;
alter table announcements enable row level security;
alter table posts enable row level security;
alter table training_plans enable row level security;
alter table workouts enable row level security;
alter table plan_assignments enable row level security;
alter table workout_logs enable row level security;

create policy profiles_select on profiles for select
  using (can_view_athlete(auth.uid(), id));
create policy profiles_update_self on profiles for update
  using (id = auth.uid() or is_coach(auth.uid()));

create policy guardian_links_select on guardian_links for select
  using (guardian_id = auth.uid() or can_view_athlete(auth.uid(), athlete_id));

create policy practices_select on practices for select using (true);
create policy practices_write on practices for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create policy attendance_select on attendance for select
  using (can_view_athlete(auth.uid(), athlete_id));
create policy attendance_write on attendance for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create policy announcements_select on announcements for select
  using (published_at is not null or is_coach(auth.uid()));
create policy announcements_write on announcements for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create policy posts_select on posts for select
  using (published_at is not null or is_coach(auth.uid()));
create policy posts_write on posts for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create policy training_plans_select on training_plans for select
  using (is_coach(auth.uid())
     or exists (select 1 from plan_assignments
                where plan_id = training_plans.id and athlete_id = auth.uid()));
create policy training_plans_write on training_plans for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create policy workouts_select on workouts for select
  using (is_coach(auth.uid())
     or exists (select 1 from plan_assignments
                where plan_id = workouts.plan_id and athlete_id = auth.uid()));
create policy workouts_write on workouts for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create policy plan_assignments_select on plan_assignments for select
  using (can_view_athlete(auth.uid(), athlete_id));
create policy plan_assignments_write on plan_assignments for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create policy workout_logs_select on workout_logs for select
  using (can_view_athlete(auth.uid(), athlete_id));
create policy workout_logs_write on workout_logs for all
  using (athlete_id = auth.uid()) with check (athlete_id = auth.uid());

-- ============================================================
-- 0002_invite_codes.sql
-- ============================================================
-- Access model: sign in with Apple/Google, then redeem a code issued after the
-- family registers on the website. The code carries the role, so the client must
-- never be able to write profiles.role directly.

-- Roles are assigned by redeem_invite_code() alone. Without this, any signed-in
-- user could promote themselves: update profiles set role = 'admin'.
revoke update on profiles from authenticated;
grant update (full_name, phone, graduation_year, date_of_birth)
  on profiles to authenticated;

create table invite_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  role app_role not null,
  full_name text not null,
  season text not null,
  -- Pairs an athlete's code with their parent's so the guardian link forms
  -- whichever of the two signs in first.
  family_id uuid,
  expires_at timestamptz,
  created_by uuid not null references profiles on delete restrict,
  created_at timestamptz not null default now(),
  redeemed_by uuid references profiles on delete set null,
  redeemed_at timestamptz,
  constraint invite_codes_role_allowed
    check (role in ('athlete', 'private_client', 'parent', 'coach'))
);

create index on invite_codes (family_id);

alter table invite_codes enable row level security;

-- Only staff touch this table directly; redemption goes through the function
-- below, so an athlete can never read or enumerate unredeemed codes.
create policy invite_codes_coach_all on invite_codes for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create or replace function redeem_invite_code(p_code text)
returns profiles
language plpgsql security definer set search_path = public as $$
declare
  v_invite invite_codes%rowtype;
  v_profile profiles%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  if exists (select 1 from profiles where id = auth.uid()) then
    raise exception 'This account is already set up';
  end if;

  select * into v_invite
    from invite_codes
   where code = upper(btrim(p_code))
     and redeemed_at is null
   for update;

  if not found then
    raise exception 'That code is not valid, or it has already been used';
  end if;

  if v_invite.expires_at is not null and v_invite.expires_at < now() then
    raise exception 'That code has expired';
  end if;

  insert into profiles (id, full_name, role)
  values (auth.uid(), v_invite.full_name, v_invite.role)
  returning * into v_profile;

  update invite_codes
     set redeemed_by = auth.uid(), redeemed_at = now()
   where id = v_invite.id;

  -- Link every redeemed parent in this family to every redeemed athlete,
  -- so the pair connects regardless of who signs in first.
  if v_invite.family_id is not null then
    insert into guardian_links (athlete_id, guardian_id)
    select athlete.redeemed_by, parent.redeemed_by
      from invite_codes athlete
      join invite_codes parent on parent.family_id = athlete.family_id
     where athlete.family_id = v_invite.family_id
       and athlete.role in ('athlete', 'private_client')
       and athlete.redeemed_by is not null
       and parent.role = 'parent'
       and parent.redeemed_by is not null
    on conflict (athlete_id, guardian_id) do nothing;
  end if;

  return v_profile;
end;
$$;

revoke all on function redeem_invite_code(text) from public, anon;
grant execute on function redeem_invite_code(text) to authenticated;

-- ============================================================
-- 0003_code_generation.sql
-- ============================================================
-- Coaches issue codes from the app after a family registers on the website.

-- 10 characters from a 16-symbol alphabet with no I, O, 0 or 1, so a code read
-- off a phone or copied out of an email is not ambiguous. ~1.1e12 combinations,
-- and every code is single-use.
create or replace function random_code() returns text
language sql volatile as $$
  with source as (select replace(gen_random_uuid()::text, '-', '') as hex)
  select string_agg(
           substr('ABCDEFGHJKLMNPQR', ('x' || substr(hex, i, 1))::bit(4)::int + 1, 1),
           '' order by i
         )
    from source, generate_series(1, 10) as i;
$$;

-- Issues an athlete code and a parent code sharing one family_id, so the
-- guardian link forms regardless of which of the two signs in first.
create or replace function create_family_codes(
  p_full_name text,
  p_season text,
  p_athlete_role app_role default 'athlete',
  p_expires_at timestamptz default null
)
returns table (athlete_code text, parent_code text)
language plpgsql security definer set search_path = public as $$
declare
  v_family uuid := gen_random_uuid();
  v_athlete text;
  v_parent text;
  v_name text := btrim(coalesce(p_full_name, ''));
begin
  if not is_coach(auth.uid()) then
    raise exception 'Only coaches can create invite codes';
  end if;

  if v_name = '' then
    raise exception 'An athlete name is required';
  end if;

  if p_athlete_role not in ('athlete', 'private_client') then
    raise exception 'Codes pair a parent with an athlete or a one-on-one client';
  end if;

  loop
    v_athlete := random_code();
    exit when not exists (select 1 from invite_codes where code = v_athlete);
  end loop;

  loop
    v_parent := random_code();
    exit when not exists (select 1 from invite_codes where code = v_parent);
  end loop;

  insert into invite_codes (code, role, full_name, season, family_id, expires_at, created_by)
  values
    (v_athlete, p_athlete_role, v_name, p_season, v_family, p_expires_at, auth.uid()),
    (v_parent, 'parent', v_name || ' (parent)', p_season, v_family, p_expires_at, auth.uid());

  athlete_code := v_athlete;
  parent_code := v_parent;
  return next;
end;
$$;

revoke all on function create_family_codes(text, text, app_role, timestamptz) from public, anon;
grant execute on function create_family_codes(text, text, app_role, timestamptz) to authenticated;

-- ============================================================
-- 0004_athlete_profiles.sql
-- ============================================================
-- The intake form an athlete (or their guardian) fills in after redeeming a code.
-- This is the one place the app holds health information about a minor, so it is
-- a separate table behind can_view_athlete() rather than columns on profiles:
-- the athlete, their linked guardians, and staff. Nobody else, ever.

alter table profiles add column onboarded_at timestamptz;

-- Self-service columns stay explicitly granted; role is still function-only.
grant update (onboarded_at) on profiles to authenticated;

create table athlete_profiles (
  athlete_id uuid primary key references profiles on delete cascade,
  school text,
  grade text,
  goals text,
  injury_history text,
  medical_notes text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  updated_at timestamptz not null default now(),
  updated_by uuid references profiles on delete set null
);

create table personal_bests (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references profiles on delete cascade,
  event text not null,
  result_seconds int not null check (result_seconds > 0),
  recorded_on date,
  meet_name text,
  created_at timestamptz not null default now(),
  -- One current best per event. Running a faster time updates the row.
  unique (athlete_id, event)
);

create index on personal_bests (athlete_id);

alter table athlete_profiles enable row level security;
alter table personal_bests enable row level security;

-- can_view_athlete() is already the athlete, their guardians, and staff, which
-- is exactly who may read and edit an intake form. Parents fill these in for
-- younger runners, so write access matches read access.
create policy athlete_profiles_select on athlete_profiles for select
  using (can_view_athlete(auth.uid(), athlete_id));
create policy athlete_profiles_insert on athlete_profiles for insert
  with check (can_view_athlete(auth.uid(), athlete_id));
create policy athlete_profiles_update on athlete_profiles for update
  using (can_view_athlete(auth.uid(), athlete_id))
  with check (can_view_athlete(auth.uid(), athlete_id));

create policy personal_bests_select on personal_bests for select
  using (can_view_athlete(auth.uid(), athlete_id));
create policy personal_bests_write on personal_bests for all
  using (can_view_athlete(auth.uid(), athlete_id))
  with check (can_view_athlete(auth.uid(), athlete_id));

create or replace function touch_athlete_profile() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

create trigger athlete_profiles_touch
  before insert or update on athlete_profiles
  for each row execute function touch_athlete_profile();

-- ============================================================
-- 0005_meetings.sql
-- ============================================================
-- One-on-one meetings. The coach publishes open times and a family claims one,
-- rather than trading messages about when everyone is free. A slot is open while
-- booked_for is null; claiming it is a single atomic update.

create type meeting_mode as enum ('in_person', 'video', 'phone');

create table meeting_slots (
  id uuid primary key default gen_random_uuid(),
  starts_at timestamptz not null,
  duration_minutes int not null default 30 check (duration_minutes between 5 and 240),
  mode meeting_mode not null default 'in_person',
  location text,
  notes text,
  created_by uuid not null references profiles on delete restrict,
  created_at timestamptz not null default now(),

  -- Booking. booked_for is the athlete the meeting is about; booked_by is
  -- whoever claimed it, which for a younger runner is usually the parent.
  booked_for uuid references profiles on delete cascade,
  booked_by uuid references profiles on delete set null,
  booked_at timestamptz,
  topic text,

  constraint meeting_slots_booking_complete
    check ((booked_for is null) = (booked_at is null))
);

create index on meeting_slots (starts_at);
create index on meeting_slots (booked_for);

alter table meeting_slots enable row level security;

-- Families see open times and their own bookings. They must not see which other
-- athletes are meeting the coach, so a booked slot is visible only to that
-- athlete's side and to staff.
create policy meeting_slots_select on meeting_slots for select
  using (
    is_coach(auth.uid())
    or booked_for is null
    or can_view_athlete(auth.uid(), booked_for)
  );

-- Only staff create or delete slots; booking happens through the functions below
-- so a family can never write an arbitrary row.
create policy meeting_slots_write on meeting_slots for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

create or replace function book_meeting_slot(
  p_slot uuid,
  p_athlete uuid,
  p_topic text default null
) returns meeting_slots
language plpgsql security definer set search_path = public as $$
declare
  v_slot meeting_slots%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  -- An athlete books for themselves; a guardian books for their own athlete.
  if not can_view_athlete(auth.uid(), p_athlete) then
    raise exception 'You can only book a meeting for your own athlete';
  end if;

  -- Locking here is what stops two families claiming the same time.
  select * into v_slot from meeting_slots where id = p_slot for update;

  if not found then
    raise exception 'That time is no longer available';
  end if;

  if v_slot.booked_for is not null then
    raise exception 'That time has already been taken';
  end if;

  if v_slot.starts_at < now() then
    raise exception 'That time has already passed';
  end if;

  update meeting_slots
     set booked_for = p_athlete,
         booked_by = auth.uid(),
         booked_at = now(),
         topic = nullif(btrim(coalesce(p_topic, '')), '')
   where id = p_slot
  returning * into v_slot;

  return v_slot;
end;
$$;

create or replace function cancel_meeting_booking(p_slot uuid)
returns meeting_slots
language plpgsql security definer set search_path = public as $$
declare
  v_slot meeting_slots%rowtype;
begin
  select * into v_slot from meeting_slots where id = p_slot for update;

  if not found or v_slot.booked_for is null then
    raise exception 'That meeting is not booked';
  end if;

  if not can_view_athlete(auth.uid(), v_slot.booked_for) then
    raise exception 'You cannot cancel someone else''s meeting';
  end if;

  -- Cancelling releases the time back to the pool rather than deleting it.
  update meeting_slots
     set booked_for = null, booked_by = null, booked_at = null, topic = null
   where id = p_slot
  returning * into v_slot;

  return v_slot;
end;
$$;

revoke all on function book_meeting_slot(uuid, uuid, text) from public, anon;
revoke all on function cancel_meeting_booking(uuid) from public, anon;
grant execute on function book_meeting_slot(uuid, uuid, text) to authenticated;
grant execute on function cancel_meeting_booking(uuid) to authenticated;

-- ============================================================
-- 0006_photos.sql
-- ============================================================
-- Clinic photo gallery. These are pictures of minors, so the bucket is private
-- and the app hands out short-lived signed URLs; there is no public link that
-- could be forwarded outside the clinic. Staff upload, everyone in the clinic
-- looks — athletes cannot post pictures of each other.

insert into storage.buckets (id, name, public)
values ('clinic-photos', 'clinic-photos', false)
on conflict (id) do nothing;

create table photos (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  caption text,
  taken_on date,
  practice_id uuid references practices on delete set null,
  audience audience not null default 'clinic',
  uploaded_by uuid not null references profiles on delete restrict,
  created_at timestamptz not null default now()
);

create index on photos (created_at desc);

alter table photos enable row level security;

-- Anyone who has redeemed a code has a profile; that is the clinic.
create policy photos_select on photos for select
  using (exists (select 1 from profiles where id = auth.uid()));
create policy photos_write on photos for all
  using (is_coach(auth.uid())) with check (is_coach(auth.uid()));

-- Storage mirrors the table: clinic members read, staff write.
create policy "clinic photos are readable by members"
  on storage.objects for select
  using (
    bucket_id = 'clinic-photos'
    and exists (select 1 from profiles where id = auth.uid())
  );

create policy "clinic photos are written by staff"
  on storage.objects for insert
  with check (bucket_id = 'clinic-photos' and is_coach(auth.uid()));

create policy "clinic photos are replaced by staff"
  on storage.objects for update
  using (bucket_id = 'clinic-photos' and is_coach(auth.uid()))
  with check (bucket_id = 'clinic-photos' and is_coach(auth.uid()));

create policy "clinic photos are removed by staff"
  on storage.objects for delete
  using (bucket_id = 'clinic-photos' and is_coach(auth.uid()));

-- ============================================================
-- 0007_account_and_audit.sql
-- ============================================================
-- Store-compliance groundwork.
--
-- Apple requires that an account created in the app can be deleted from inside
-- the app (Guideline 5.1.1(v)), and both stores expect a real export/erasure
-- path for a family's data. This migration adds the three server-side pieces
-- the app cannot do from the client: deleting the auth user, assembling an
-- export, and recording who read a minor's medical information.

-- ---------------------------------------------------------------------------
-- Audit log. Reading a child's medical record is an event worth keeping.
-- ---------------------------------------------------------------------------

create table audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references profiles on delete set null,
  action text not null,
  table_name text not null,
  record_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index on audit_log (record_id, created_at desc);
create index on audit_log (actor_id, created_at desc);

alter table audit_log enable row level security;

-- Staff can read the trail; nobody writes it from the client. Entries are
-- inserted by the SECURITY DEFINER functions below, which run as the owner.
create policy audit_log_select on audit_log for select
  using (is_coach(auth.uid()));

revoke insert, update, delete on audit_log from authenticated, anon;

-- ---------------------------------------------------------------------------
-- Guardian consent for a minor's medical fields.
-- ---------------------------------------------------------------------------

alter table athlete_profiles
  add column guardian_consent_by uuid references profiles on delete set null,
  add column guardian_consent_at timestamptz;

comment on column athlete_profiles.guardian_consent_at is
  'When a guardian confirmed the health information may be held.';

-- ---------------------------------------------------------------------------
-- Staff reads of an intake form go through this, so they can be logged.
-- ---------------------------------------------------------------------------

create or replace function staff_view_athlete_profile(p_athlete uuid)
returns athlete_profiles
language plpgsql security definer set search_path = public as $$
declare
  v_profile athlete_profiles%rowtype;
begin
  if not can_view_athlete(auth.uid(), p_athlete) then
    raise exception 'You cannot view that athlete';
  end if;

  select * into v_profile from athlete_profiles where athlete_id = p_athlete;

  -- Only staff reads are noteworthy. A family reading their own record is not
  -- an access event, and logging it would bury the reads that matter.
  if is_coach(auth.uid()) then
    insert into audit_log (actor_id, action, table_name, record_id)
    values (auth.uid(), 'read', 'athlete_profiles', p_athlete);
  end if;

  return v_profile;
end;
$$;

revoke all on function staff_view_athlete_profile(uuid) from public, anon;
grant execute on function staff_view_athlete_profile(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Export. A family can take their data with them.
-- ---------------------------------------------------------------------------

create or replace function export_my_data()
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid := auth.uid();
  v_out jsonb;
begin
  if v_id is null then
    raise exception 'Not signed in';
  end if;

  select jsonb_build_object(
    'exported_at', now(),
    'account', (select to_jsonb(p) from profiles p where p.id = v_id),
    'athlete_profile', (select to_jsonb(a) from athlete_profiles a where a.athlete_id = v_id),
    'personal_bests', coalesce((select jsonb_agg(to_jsonb(b)) from personal_bests b where b.athlete_id = v_id), '[]'::jsonb),
    'workout_logs', coalesce((select jsonb_agg(to_jsonb(l)) from workout_logs l where l.athlete_id = v_id), '[]'::jsonb),
    'attendance', coalesce((select jsonb_agg(to_jsonb(t)) from attendance t where t.athlete_id = v_id), '[]'::jsonb),
    'meetings', coalesce((select jsonb_agg(to_jsonb(m)) from meeting_slots m where m.booked_for = v_id), '[]'::jsonb),
    'guardian_links', coalesce((select jsonb_agg(to_jsonb(g)) from guardian_links g
                                 where g.guardian_id = v_id or g.athlete_id = v_id), '[]'::jsonb)
  ) into v_out;

  return v_out;
end;
$$;

revoke all on function export_my_data() from public, anon;
grant execute on function export_my_data() to authenticated;

-- ---------------------------------------------------------------------------
-- Deletion. Apple requires this to be reachable from inside the app, and to
-- actually remove the account rather than deactivate it.
-- ---------------------------------------------------------------------------

create or replace function delete_my_account()
returns void
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid := auth.uid();
  v_role app_role;
  v_heir uuid;
begin
  if v_id is null then
    raise exception 'Not signed in';
  end if;

  select role into v_role from profiles where id = v_id;
  if v_role is null then
    -- Signed in but never redeemed a code: nothing of ours to unpick.
    delete from auth.users where id = v_id;
    return;
  end if;

  if is_coach(v_id) then
    -- Practices, announcements, plans and codes are the clinic's records, not
    -- the coach's, and they are referenced with ON DELETE RESTRICT so they
    -- cannot be silently destroyed. Hand them to another member of staff.
    select id into v_heir
      from profiles
     where role in ('admin', 'coach') and id <> v_id
     order by created_at
     limit 1;

    if v_heir is null then
      raise exception 'You are the only coach on this clinic. Add another coach before deleting your account, so the schedule, plans and announcements are not lost.';
    end if;

    update practices set created_by = v_heir where created_by = v_id;
    update attendance set recorded_by = v_heir where recorded_by = v_id;
    update announcements set author_id = v_heir where author_id = v_id;
    update posts set author_id = v_heir where author_id = v_id;
    update training_plans set created_by = v_heir where created_by = v_id;
    update plan_assignments set assigned_by = v_heir where assigned_by = v_id;
    update invite_codes set created_by = v_heir where created_by = v_id;
    update photos set uploaded_by = v_heir where uploaded_by = v_id;
    update meeting_slots set created_by = v_heir where created_by = v_id;
  end if;

  insert into audit_log (actor_id, action, table_name, record_id, metadata)
  values (null, 'delete_account', 'profiles', v_id,
          jsonb_build_object('role', v_role, 'reassigned_to', v_heir));

  -- Everything personal hangs off profiles or auth.users by ON DELETE CASCADE:
  -- the intake form, personal bests, training logs, attendance, guardian links,
  -- and any meeting booked for them.
  delete from auth.users where id = v_id;
end;
$$;

revoke all on function delete_my_account() from public, anon;
grant execute on function delete_my_account() to authenticated;

-- ============================================================
-- 0008_injuries_only.sql
-- ============================================================
-- The clinic collects less about a minor, not more.
--
-- Medical conditions, allergies and medication come out of the app entirely —
-- the coach gathers those from parents directly, which keeps the most sensitive
-- category of a child's information off a phone and out of this database.
--
-- Injuries stay, because they change what a coach asks an athlete to run today,
-- and they are the thing a training app has an actual reason to hold. The one
-- free-text field is split in two: what is wrong now, and what has happened
-- before. A coach at the trailhead needs the first at a glance.

alter table athlete_profiles drop column medical_notes;

alter table athlete_profiles add column current_injuries text;

comment on column athlete_profiles.current_injuries is
  'What is bothering the athlete right now. Shown first to staff, because it is
   what changes today''s session.';

comment on column athlete_profiles.injury_history is
  'Injuries that have healed. Context for a coach reading a pattern, not a
   reason to change today''s session.';

-- The in-app consent columns go with them. The clinic records guardian consent
-- by talking to parents, so leaving unused columns here would be dead schema
-- claiming a safeguard the app does not actually perform.
alter table athlete_profiles
  drop column guardian_consent_by,
  drop column guardian_consent_at;

-- ============================================================
-- 0009_no_health_data.sql
-- ============================================================
-- The app stops holding health information about children altogether.
--
-- Injuries follow medical conditions out of the database. The coach handles
-- both by talking to parents, which is where that conversation belongs. What is
-- left on the intake form is what the app genuinely needs to run a clinic:
-- where an athlete goes to school, what they are aiming at, and who to call.
--
-- This is not only a smaller form. It changes what the clinic has to declare to
-- Apple and Google, and it means a lost phone or a breached database exposes no
-- child's health history, because there is none to expose.

alter table athlete_profiles
  drop column current_injuries,
  drop column injury_history;

-- ============================================================
-- 0010_audience_and_parent_logs.sql
-- ============================================================
-- Two holes between what the app promises and what the database enforces.
--
-- 1. Every practice, announcement, post and photo already carries an audience,
--    and a coach picks one when posting — but nothing ever read it. A "Coaches
--    only" announcement was visible to every athlete in the clinic, and a
--    one-on-one client saw the whole summer group's content. The control was
--    real in the UI and imaginary in the database.
--
-- 2. Parents could not log a run. Plenty of these athletes have no phone, so a
--    parent entering the run is not an edge case — without it those athletes
--    simply have no training history.

-- ---------------------------------------------------------------------------
-- Who an audience reaches.
-- ---------------------------------------------------------------------------

-- Written once and called from every policy, so the rule cannot drift between
-- practices and announcements.
--
-- A parent sees whatever their own athletes see, which is what makes a
-- one-on-one client's parent see private content and nothing from the clinic.
-- 'everyone' means everyone, because that is what the coach picked.
create or replace function can_see_audience(uid uuid, aud audience)
returns boolean
language sql stable security definer set search_path = public as $$
  select case
    when uid is null then false
    when is_coach(uid) then true
    when aud = 'coaches' then false
    when aud = 'everyone' then exists (select 1 from profiles where id = uid)
    when aud = 'clinic' then
      exists (select 1 from profiles where id = uid and role = 'athlete')
      or exists (select 1 from guardian_links g
                   join profiles a on a.id = g.athlete_id
                  where g.guardian_id = uid and a.role = 'athlete')
    when aud = 'private' then
      exists (select 1 from profiles where id = uid and role = 'private_client')
      or exists (select 1 from guardian_links g
                   join profiles a on a.id = g.athlete_id
                  where g.guardian_id = uid and a.role = 'private_client')
    else false
  end;
$$;

drop policy practices_select on practices;
create policy practices_select on practices for select
  using (can_see_audience(auth.uid(), audience));

drop policy announcements_select on announcements;
create policy announcements_select on announcements for select
  using (
    (published_at is not null and can_see_audience(auth.uid(), audience))
    or is_coach(auth.uid())
  );

drop policy posts_select on posts;
create policy posts_select on posts for select
  using (
    (published_at is not null and can_see_audience(auth.uid(), audience))
    or is_coach(auth.uid())
  );

drop policy photos_select on photos;
create policy photos_select on photos for select
  using (can_see_audience(auth.uid(), audience));

-- ---------------------------------------------------------------------------
-- Parents logging runs.
-- ---------------------------------------------------------------------------

alter table workout_logs
  add column logged_by uuid references profiles on delete set null;

comment on column workout_logs.logged_by is
  'Who entered the log. Differs from athlete_id when a parent entered it for
   their athlete, which the coach''s view shows.';

-- Set server-side rather than trusted from the client, so attribution cannot be
-- forged by posting someone else''s id.
create or replace function stamp_workout_log() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.logged_by := auth.uid();
  return new;
end;
$$;

create trigger workout_logs_stamp
  before insert or update on workout_logs
  for each row execute function stamp_workout_log();

-- The athlete, or a guardian linked to them. Deliberately not coaches: the
-- training log is the athlete's own account of the run, and a coach writing
-- into it would make "who has logged this week" meaningless.
drop policy workout_logs_write on workout_logs;
create policy workout_logs_write on workout_logs for all
  using (
    athlete_id = auth.uid()
    or exists (select 1 from guardian_links
                where athlete_id = workout_logs.athlete_id
                  and guardian_id = auth.uid())
  )
  with check (
    athlete_id = auth.uid()
    or exists (select 1 from guardian_links
                where athlete_id = workout_logs.athlete_id
                  and guardian_id = auth.uid())
  );

-- ============================================================
-- 0011_assistant_coaches.sql
-- ============================================================
-- Assistant coaches.
--
-- The clinic has a head coach and two assistants. Both run practices, write
-- training and post announcements, so is_coach() still covers all of them.
-- What only the head coach does is hand out access to the clinic: issuing a
-- code is how a family gets in, and that stays with one person.
--
-- 'admin' is the head coach, 'coach' an assistant. No new role is needed.

create or replace function is_head_coach(uid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = uid and role = 'admin');
$$;

-- Assistants no longer read or write the code table. An assistant who needs a
-- family let in asks the head coach, which is the same conversation that
-- happens now over text.
drop policy invite_codes_coach_all on invite_codes;
create policy invite_codes_head_coach_all on invite_codes for all
  using (is_head_coach(auth.uid())) with check (is_head_coach(auth.uid()));

create or replace function create_family_codes(
  p_full_name text,
  p_season text,
  p_athlete_role app_role default 'athlete',
  p_expires_at timestamptz default null
)
returns table (athlete_code text, parent_code text)
language plpgsql security definer set search_path = public as $$
declare
  v_family uuid := gen_random_uuid();
  v_athlete text;
  v_parent text;
  v_name text := btrim(coalesce(p_full_name, ''));
begin
  if not is_head_coach(auth.uid()) then
    raise exception 'Only the head coach can create invite codes';
  end if;

  if v_name = '' then
    raise exception 'An athlete name is required';
  end if;

  if p_athlete_role not in ('athlete', 'private_client') then
    raise exception 'Codes pair a parent with an athlete or a one-on-one client';
  end if;

  loop
    v_athlete := random_code();
    exit when not exists (select 1 from invite_codes where code = v_athlete);
  end loop;

  loop
    v_parent := random_code();
    exit when not exists (select 1 from invite_codes where code = v_parent);
  end loop;

  insert into invite_codes (code, role, full_name, season, family_id, expires_at, created_by)
  values
    (v_athlete, p_athlete_role, v_name, p_season, v_family, p_expires_at, auth.uid()),
    (v_parent, 'parent', v_name || ' (parent)', p_season, v_family, p_expires_at, auth.uid());

  athlete_code := v_athlete;
  parent_code := v_parent;
  return next;
end;
$$;

revoke all on function create_family_codes(text, text, app_role, timestamptz) from public, anon;
grant execute on function create_family_codes(text, text, app_role, timestamptz) to authenticated;

-- ============================================================
-- 0012_push_notifications.sql
-- ============================================================
-- Push notifications.
--
-- An announcement nobody sees is not an announcement, and "practice moved to
-- 7am" is exactly the message that has to arrive before someone drives to the
-- old time. This adds the token, the per-category preferences, and one function
-- that decides who a push actually goes to.

alter table profiles
  add column push_token text,
  add column notification_prefs jsonb not null default
    '{"announcements": true, "practices": true, "workouts": true, "learn": false, "meetings": true}'::jsonb;

-- Self-service, like name and phone. Role stays function-only.
grant update (push_token, notification_prefs) on profiles to authenticated;

create index on profiles (push_token) where push_token is not null;

/**
 * Tokens to push a given item to.
 *
 * The audience rule lives in can_see_audience() and is called here rather than
 * restated, so a push can never reach someone who cannot open the thing it is
 * telling them about. Preferences are checked on top: a category switched off
 * means no push, but the row is still visible in the app.
 */
create or replace function push_recipients(p_audience audience, p_pref text)
returns table (profile_id uuid, push_token text)
language sql stable security definer set search_path = public as $$
  select p.id, p.push_token
    from profiles p
   where p.push_token is not null
     and can_see_audience(p.id, p_audience)
     and coalesce((p.notification_prefs ->> p_pref)::boolean, false);
$$;

-- Only the service role, from an Edge Function, may enumerate tokens. This must
-- never be reachable with the anon key: it would hand any signed-in athlete a
-- list of push tokens for the whole clinic.
revoke all on function push_recipients(audience, text) from public, anon, authenticated;

-- ============================================================
-- 0013_per_athlete_audience.sql
-- ============================================================
-- One-on-one content is for one athlete, not for "the one-on-one clients".
--
-- A single 'private' bucket meant every private client saw every other private
-- client's announcements, practices and photos. Their training was already
-- separate, because a plan is assigned to a named athlete — but everything else
-- was shared between people who have no connection to each other and are paying
-- for individual coaching.
--
-- A row can now name the athlete it is for. When it does, that beats the
-- audience: only that athlete, their guardians, and staff ever see it.

alter table announcements add column audience_athlete_id uuid references profiles on delete cascade;
alter table practices    add column audience_athlete_id uuid references profiles on delete cascade;
alter table posts        add column audience_athlete_id uuid references profiles on delete cascade;
alter table photos       add column audience_athlete_id uuid references profiles on delete cascade;

create index on announcements (audience_athlete_id);
create index on practices (audience_athlete_id);
create index on posts (audience_athlete_id);
create index on photos (audience_athlete_id);

comment on column announcements.audience_athlete_id is
  'When set, this is for that athlete alone and the audience column is ignored.';

/**
 * Whether a row reaches someone: the audience rule, plus the athlete a row may
 * be pinned to.
 *
 * can_view_athlete() is reused for the pinned case rather than restated, so a
 * private announcement reaches exactly the people who can already see that
 * athlete's records — the athlete, their guardians, and staff.
 */
create or replace function can_see_item(uid uuid, aud audience, target uuid)
returns boolean
language sql stable security definer set search_path = public as $$
  select case
    when uid is null then false
    when is_coach(uid) then true
    -- Named athlete wins. A row for Lena is not for "one-on-one clients".
    when target is not null then can_view_athlete(uid, target)
    else can_see_audience(uid, aud)
  end;
$$;

drop policy practices_select on practices;
create policy practices_select on practices for select
  using (can_see_item(auth.uid(), audience, audience_athlete_id));

drop policy announcements_select on announcements;
create policy announcements_select on announcements for select
  using (
    (published_at is not null and can_see_item(auth.uid(), audience, audience_athlete_id))
    or is_coach(auth.uid())
  );

drop policy posts_select on posts;
create policy posts_select on posts for select
  using (
    (published_at is not null and can_see_item(auth.uid(), audience, audience_athlete_id))
    or is_coach(auth.uid())
  );

drop policy photos_select on photos;
create policy photos_select on photos for select
  using (can_see_item(auth.uid(), audience, audience_athlete_id));

-- Push has to follow the same rule, or a notification would announce something
-- the person cannot open.
--
-- The two-argument version is dropped rather than left alongside: with a
-- defaulted third parameter the old call would match both and Postgres refuses
-- it as ambiguous.
drop function if exists push_recipients(audience, text);

create or replace function push_recipients(p_audience audience, p_pref text, p_athlete uuid default null)
returns table (profile_id uuid, push_token text)
language sql stable security definer set search_path = public as $$
  select p.id, p.push_token
    from profiles p
   where p.push_token is not null
     and can_see_item(p.id, p_audience, p_athlete)
     and coalesce((p.notification_prefs ->> p_pref)::boolean, false);
$$;

revoke all on function push_recipients(audience, text, uuid) from public, anon, authenticated;

-- ============================================================
-- 0014_error_reports.sql
-- ============================================================
-- Crash reports, kept in the clinic's own database.
--
-- The obvious answer is Sentry, and for an app with native crashes to chase it
-- would be the right one. It is the wrong trade here: this app's privacy policy
-- says there is no third-party analytics in it, both stores are told the same,
-- and adding an SDK that ships diagnostics off to another company would make
-- that untrue and change the declarations. A table the clinic already owns
-- catches the JavaScript errors families actually hit, and costs nothing in
-- either privacy or paperwork.
--
-- If native crash coverage is ever needed, Sentry is the upgrade — but the
-- store answers for diagnostics have to change in the same commit.

create table app_errors (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references profiles on delete set null,
  message text not null,
  stack text,
  route text,
  platform text,
  app_version text,
  created_at timestamptz not null default now()
);

create index on app_errors (created_at desc);

alter table app_errors enable row level security;

-- Anyone signed in can report the error they just hit; nobody can read the
-- reports but staff, and nobody can edit or delete them at all.
create policy app_errors_insert on app_errors for insert
  with check (profile_id is null or profile_id = auth.uid());

create policy app_errors_select on app_errors for select
  using (is_coach(auth.uid()));

revoke update, delete on app_errors from authenticated, anon;

-- ============================================================
-- 0015_pinned_and_completions.sql
-- ============================================================
-- Pinned announcements, and tracking who has worked through a Learn session.

-- ---------------------------------------------------------------------------
-- Pinning.
-- ---------------------------------------------------------------------------

alter table announcements add column pinned boolean not null default false;

-- Pinned items are read first and are usually few, so the index only covers
-- them rather than every announcement the clinic has ever posted.
create index on announcements (pinned, published_at desc) where pinned;

comment on column announcements.pinned is
  'Stays at the top of the family home screen until the coach unpins it. For the
   thing that must not scroll away — a time change, a meet location.';

-- ---------------------------------------------------------------------------
-- Learn completions.
-- ---------------------------------------------------------------------------

create table lesson_completions (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references posts on delete cascade,
  profile_id uuid not null references profiles on delete cascade,
  completed_at timestamptz not null default now(),
  unique (post_id, profile_id)
);

create index on lesson_completions (profile_id);
create index on lesson_completions (post_id);

alter table lesson_completions enable row level security;

-- You mark your own. Staff and a guardian can see whether it was marked, since
-- that is the point of tracking it, but neither can mark it for someone else —
-- a coach ticking it off would make the count meaningless.
create policy lesson_completions_select on lesson_completions for select
  using (can_view_athlete(auth.uid(), profile_id));

create policy lesson_completions_write on lesson_completions for all
  using (profile_id = auth.uid()) with check (profile_id = auth.uid());

-- ============================================================
-- 0016_workout_distance_range.sql
-- ============================================================
-- Mileage ranges on a planned workout.
--
-- A coach writing "4-6 miles" had nowhere to put it: distance_miles is one
-- number, so the editor refused the dash. This adds the far end of the range
-- and leaves the existing column as the near end, which keeps every workout
-- already written valid and every query reading distance_miles correct.
--
-- It stays two numbers rather than becoming free text so the app can still
-- display mileage consistently and add up a week of it later. Anything that is
-- not a distance — intervals, time-based runs — belongs in description or
-- intensity, which already take any text.

alter table workouts add column distance_miles_max numeric(5,2);

-- A far end with no near end is meaningless, and a range that does not go
-- upwards is a typo rather than a range. Both are rejected here as well as in
-- the editor, because the editor is not the only thing that can write a row.
alter table workouts add constraint workouts_distance_range_valid check (
  distance_miles_max is null
  or (distance_miles is not null and distance_miles_max > distance_miles)
);

comment on column workouts.distance_miles is
  'Planned distance. The near end of the range when distance_miles_max is set.';
comment on column workouts.distance_miles_max is
  'Far end of a planned range, e.g. 6 for "4-6 miles". Null for a single distance.';

-- ============================================================
-- 0017_remove_from_clinic.sql
-- ============================================================
-- Removing an athlete from the clinic.
--
-- The roster could be read but never trimmed: an athlete who left, or a test
-- account, stayed on it for good. This is the head coach's counterpart to
-- issuing a code, and is held to the same rule — letting a family in and
-- taking them out both stay with one person, not every assistant.
--
-- It removes the person outright, the way delete_my_account() does for someone
-- deleting themselves: the intake form, personal bests, training logs,
-- attendance, bookings and guardian links all hang off the account by ON
-- DELETE CASCADE. Nothing an athlete can hold is ON DELETE RESTRICT — those
-- are all staff-authored columns — so no record has to be handed on first.
-- Coming back next season is a fresh sign-in and a new code.
--
-- A parent whose only athlete this is goes too. Left behind, they would open
-- an app with nothing in it and no way to tell why. A parent with another
-- athlete still in the clinic keeps their access. Only accounts whose role is
-- 'parent' are ever taken this way: a coach who is also somebody's guardian
-- must never be removed as a side effect of removing their child.
--
-- The family's unredeemed codes are cancelled as well, or a parent code still
-- sitting in someone's inbox could be redeemed later into an empty account.
--
-- p_dry_run returns who would be removed without removing anyone, so the
-- confirmation the coach reads is worked out by the same query that acts on
-- it rather than a copy of it in the app.

create or replace function remove_from_clinic(p_athlete uuid, p_dry_run boolean default false)
returns table (person_id uuid, person_name text, person_role app_role)
language plpgsql security definer set search_path = public as $$
declare
  v_role app_role;
  v_family uuid;
  v_ids uuid[];
begin
  if not is_head_coach(auth.uid()) then
    raise exception 'Only the head coach can remove someone from the clinic';
  end if;

  select p.role into v_role from profiles p where p.id = p_athlete;
  if v_role is null then
    raise exception 'That person is not on the roster';
  end if;
  if v_role not in ('athlete', 'private_client') then
    raise exception 'Only athletes and one-on-one clients are removed from the roster';
  end if;

  v_ids := array[p_athlete] || coalesce(array(
    select g.guardian_id
      from guardian_links g
      join profiles gp on gp.id = g.guardian_id and gp.role = 'parent'
     where g.athlete_id = p_athlete
       and not exists (
         select 1 from guardian_links other
          where other.guardian_id = g.guardian_id
            and other.athlete_id <> p_athlete
       )
  ), '{}');

  -- Materialised now, before anything is deleted, so a real run reports the
  -- same people a dry run does.
  return query
    select p.id, p.full_name, p.role
      from profiles p
     where p.id = any(v_ids)
     order by (p.id = p_athlete) desc, p.full_name;

  if p_dry_run then
    return;
  end if;

  select c.family_id into v_family
    from invite_codes c
   where c.redeemed_by = p_athlete and c.family_id is not null
   limit 1;
  if v_family is not null then
    delete from invite_codes c where c.family_id = v_family and c.redeemed_at is null;
  end if;

  -- Written while the rows still exist to read the roles from. The actor stays
  -- on the log; the removed people are recorded by id alone.
  insert into audit_log (actor_id, action, table_name, record_id, metadata)
  select auth.uid(), 'remove_from_clinic', 'profiles', p.id,
         jsonb_build_object('role', p.role, 'athlete', p_athlete)
    from profiles p
   where p.id = any(v_ids);

  delete from auth.users u where u.id = any(v_ids);
end;
$$;

revoke all on function remove_from_clinic(uuid, boolean) from public, anon;
grant execute on function remove_from_clinic(uuid, boolean) to authenticated;

-- ============================================================
-- 0018_practice_map_address.sql
-- ============================================================
-- A map address on a practice, so a family can tap the location and get
-- directions instead of copying the name into a maps app by hand.
--
-- location_name stays what it was — the short name people say, "Jemison
-- Trail" — and this is where the coach puts what a maps app needs: a street
-- address, or a Google or Apple Maps link pasted straight from the share
-- sheet. It is optional: left empty, the app searches the location name,
-- which is usually right for a well-known trail and never worse than nothing.
--
-- No new policy: practices are written by staff and read under the existing
-- audience rules, and this column rides along with the rest of the row.

alter table practices add column map_address text;

-- Long enough for any address or share link; short enough that nobody pastes
-- a paragraph of directions here instead of into notes.
alter table practices add constraint practices_map_address_length check (
  map_address is null or char_length(map_address) <= 500
);

comment on column practices.map_address is
  'Street address or maps link used for directions. Null means search location_name.';

-- ============================================================
-- 0019_add_athlete_to_family.sql
-- ============================================================
-- Linking a parent to a runner who is not linked yet.
--
-- Codes come one pair per child: an athlete code and a parent code that share
-- a family_id. Until now a parent was linked only when the child redeemed
-- their own code on their own phone, which left two families stranded:
--
--   * A runner with no phone of their own. Many of these athletes are young,
--     and the child never signing in meant the parent never saw their runner.
--   * A parent with a second child. redeem_invite_code() refuses an account
--     that already exists, so the second child's parent code had nowhere to go.
--
-- add_athlete_to_family() is for a signed-in parent, and takes either code:
--
--   * A parent code links them to that family's runner, exactly as the first
--     code did. If the runner has not signed in yet, the link forms when they
--     do.
--   * An athlete code creates the runner's account for them, managed by the
--     parent. Accepted only for a family whose parent code this parent has
--     already redeemed, so holding a stray athlete code is not a way to attach
--     yourself to someone else's child.
--
-- The caller's own role is never touched. The managed runner's role comes
-- from their athlete code, as every role does.

-- Defined briefly under another name and never released; cleared in case it
-- was created by hand.
drop function if exists link_another_athlete(text);

alter table profiles add column managed boolean not null default false;

comment on column profiles.managed is
  'A runner without a phone: the account was created by their parent from the
   athlete code, nobody signs in as it, and the parent does everything for them.
   Deleted along with the last parent who manages it.';

create or replace function add_athlete_to_family(p_code text)
returns text
language plpgsql security definer set search_path = public as $$
declare
  v_invite invite_codes%rowtype;
  v_athlete uuid;
  v_result text;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  if not exists (select 1 from profiles where id = auth.uid() and role = 'parent') then
    raise exception 'Only a parent account can add an athlete';
  end if;

  select * into v_invite
    from invite_codes
   where code = upper(btrim(p_code))
     and redeemed_at is null
   for update;

  if not found then
    raise exception 'That code is not valid, or it has already been used';
  end if;

  if v_invite.expires_at is not null and v_invite.expires_at < now() then
    raise exception 'That code has expired';
  end if;

  if v_invite.role = 'parent' then
    update invite_codes
       set redeemed_by = auth.uid(), redeemed_at = now()
     where id = v_invite.id;

  elsif v_invite.role in ('athlete', 'private_client') then
    if v_invite.family_id is null
       or not exists (
         select 1 from invite_codes mine
          where mine.family_id = v_invite.family_id
            and mine.role = 'parent'
            and mine.redeemed_by = auth.uid()
       ) then
      raise exception 'That athlete code is for a different family. Use the parent code that came with it first';
    end if;

    -- An account nobody signs in to: no email, no password, no identity. It
    -- exists so the runner's training, schedule and profile have an owner.
    -- The empty strings stand in for token columns Supabase's auth server
    -- reads as text and rejects as NULL.
    v_athlete := gen_random_uuid();
    insert into auth.users (
      id, instance_id, aud, role, raw_app_meta_data, raw_user_meta_data,
      confirmation_token, recovery_token, email_change_token_new, email_change,
      created_at, updated_at
    ) values (
      v_athlete, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      jsonb_build_object('provider', 'managed', 'providers', jsonb_build_array()),
      jsonb_build_object('managed_by', auth.uid()),
      '', '', '', '',
      now(), now()
    );

    insert into profiles (id, full_name, role, managed)
    values (v_athlete, v_invite.full_name, v_invite.role, true);

    update invite_codes
       set redeemed_by = v_athlete, redeemed_at = now()
     where id = v_invite.id;

  else
    raise exception 'That code cannot be used here';
  end if;

  -- Same linking as redeem_invite_code(): every redeemed parent in the family
  -- to every redeemed athlete.
  if v_invite.family_id is not null then
    insert into guardian_links (athlete_id, guardian_id)
    select athlete.redeemed_by, parent.redeemed_by
      from invite_codes athlete
      join invite_codes parent on parent.family_id = athlete.family_id
     where athlete.family_id = v_invite.family_id
       and athlete.role in ('athlete', 'private_client')
       and athlete.redeemed_by is not null
       and parent.role = 'parent'
       and parent.redeemed_by is not null
    on conflict (athlete_id, guardian_id) do nothing;
  end if;

  insert into audit_log (actor_id, action, table_name, record_id, metadata)
  values (auth.uid(), 'add_athlete_to_family', 'invite_codes', v_invite.id,
          jsonb_build_object('family_id', v_invite.family_id, 'code_role', v_invite.role,
                             'managed_athlete', v_athlete));

  -- What the app tells the parent: their runner is here now, or will be once
  -- the runner signs in with their own code.
  if v_athlete is not null then
    v_result := 'managed';
  elsif exists (
    select 1 from guardian_links gl
      join invite_codes athlete on athlete.redeemed_by = gl.athlete_id
     where gl.guardian_id = auth.uid()
       and athlete.family_id = v_invite.family_id
       and athlete.role in ('athlete', 'private_client')
  ) then
    v_result := 'linked';
  else
    v_result := 'pending';
  end if;

  return v_result;
end;
$$;

revoke all on function add_athlete_to_family(text) from public, anon;
grant execute on function add_athlete_to_family(text) to authenticated;

-- Deleting a parent's account takes the runners only they manage with it.
-- Otherwise a managed runner would be left with no one able to reach them,
-- and no way in. Unchanged from 0007 apart from that block.
create or replace function delete_my_account()
returns void
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid := auth.uid();
  v_role app_role;
  v_heir uuid;
  v_managed uuid[];
begin
  if v_id is null then
    raise exception 'Not signed in';
  end if;

  select role into v_role from profiles where id = v_id;
  if v_role is null then
    -- Signed in but never redeemed a code: nothing of ours to unpick.
    delete from auth.users where id = v_id;
    return;
  end if;

  if is_coach(v_id) then
    -- Practices, announcements, plans and codes are the clinic's records, not
    -- the coach's, and they are referenced with ON DELETE RESTRICT so they
    -- cannot be silently destroyed. Hand them to another member of staff.
    select id into v_heir
      from profiles
     where role in ('admin', 'coach') and id <> v_id
     order by created_at
     limit 1;

    if v_heir is null then
      raise exception 'You are the only coach on this clinic. Add another coach before deleting your account, so the schedule, plans and announcements are not lost.';
    end if;

    update practices set created_by = v_heir where created_by = v_id;
    update attendance set recorded_by = v_heir where recorded_by = v_id;
    update announcements set author_id = v_heir where author_id = v_id;
    update posts set author_id = v_heir where author_id = v_id;
    update training_plans set created_by = v_heir where created_by = v_id;
    update plan_assignments set assigned_by = v_heir where assigned_by = v_id;
    update invite_codes set created_by = v_heir where created_by = v_id;
    update photos set uploaded_by = v_heir where uploaded_by = v_id;
    update meeting_slots set created_by = v_heir where created_by = v_id;
  end if;

  v_managed := coalesce(array(
    select gl.athlete_id
      from guardian_links gl
      join profiles athlete on athlete.id = gl.athlete_id and athlete.managed
     where gl.guardian_id = v_id
       and not exists (
         select 1 from guardian_links other
          where other.athlete_id = gl.athlete_id
            and other.guardian_id <> v_id
       )
  ), '{}');

  insert into audit_log (actor_id, action, table_name, record_id, metadata)
  values (null, 'delete_account', 'profiles', v_id,
          jsonb_build_object('role', v_role, 'reassigned_to', v_heir,
                             'managed_runners', to_jsonb(v_managed)));

  -- Everything personal hangs off profiles or auth.users by ON DELETE CASCADE:
  -- the intake form, personal bests, training logs, attendance, guardian links,
  -- and any meeting booked for them.
  delete from auth.users where id = any(v_managed);
  delete from auth.users where id = v_id;
end;
$$;

revoke all on function delete_my_account() from public, anon;
grant execute on function delete_my_account() to authenticated;

-- ============================================================
-- 0020_claim_and_set_up_runner.sql
-- ============================================================
-- Two ways a parent reaches their runner, made distinct.
--
-- 0019 let a parent type their runner's athlete code to set up an account for
-- a runner without a phone. That made the athlete code mean two different
-- things, and the dangerous one won: a parent "claiming" a runner who did have
-- a phone, before the runner had signed in, spent the code on a managed
-- account and locked the runner out of their own.
--
-- Now:
--
--   * The athlete code, typed by a parent, only ever claims: it links them to
--     that runner and never spends the code. If the runner has not signed in
--     yet, nothing is used up and the link forms when they do.
--
--   * A runner without a phone is set up by name, with set_up_runner(). The
--     parent never needs the athlete code for it. The name starts as the one
--     the coach typed when issuing the codes, which my_runners_to_set_up()
--     offers, so it is usually a single tap.
--
-- Both accept only families whose parent code this parent has redeemed. The
-- caller's own role is never touched; a managed runner's role is the one their
-- family's athlete code carries.

-- ---------------------------------------------------------------------------
-- Claiming, and adding another child.
-- ---------------------------------------------------------------------------

create or replace function add_athlete_to_family(p_code text)
returns text
language plpgsql security definer set search_path = public as $$
declare
  v_invite invite_codes%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  if not exists (select 1 from profiles where id = auth.uid() and role = 'parent') then
    raise exception 'Only a parent account can add an athlete';
  end if;

  -- Not filtered on redeemed_at: claiming a runner who has already signed in
  -- is the point of an athlete code here.
  select * into v_invite
    from invite_codes
   where code = upper(btrim(p_code))
   for update;

  if not found then
    raise exception 'That code is not valid. Check it against your registration confirmation';
  end if;

  if v_invite.role = 'parent' then
    if v_invite.redeemed_at is not null then
      raise exception 'That parent code has already been used';
    end if;
    if v_invite.expires_at is not null and v_invite.expires_at < now() then
      raise exception 'That code has expired';
    end if;

    update invite_codes
       set redeemed_by = auth.uid(), redeemed_at = now()
     where id = v_invite.id;

  elsif v_invite.role in ('athlete', 'private_client') then
    if v_invite.family_id is null
       or not exists (
         select 1 from invite_codes mine
          where mine.family_id = v_invite.family_id
            and mine.role = 'parent'
            and mine.redeemed_by = auth.uid()
       ) then
      raise exception 'That athlete code is from a different registration than your parent code. Enter the parent code that came with it first';
    end if;
    -- Nothing is written to the code. Claimed or not, it stays the runner's.

  else
    raise exception 'That code cannot be used here';
  end if;

  if v_invite.family_id is not null then
    insert into guardian_links (athlete_id, guardian_id)
    select athlete.redeemed_by, parent.redeemed_by
      from invite_codes athlete
      join invite_codes parent on parent.family_id = athlete.family_id
     where athlete.family_id = v_invite.family_id
       and athlete.role in ('athlete', 'private_client')
       and athlete.redeemed_by is not null
       and parent.role = 'parent'
       and parent.redeemed_by is not null
    on conflict (athlete_id, guardian_id) do nothing;
  end if;

  if v_invite.role = 'parent' then
    insert into audit_log (actor_id, action, table_name, record_id, metadata)
    values (auth.uid(), 'add_athlete_to_family', 'invite_codes', v_invite.id,
            jsonb_build_object('family_id', v_invite.family_id));
  end if;

  if exists (
    select 1 from guardian_links gl
      join invite_codes athlete on athlete.redeemed_by = gl.athlete_id
     where gl.guardian_id = auth.uid()
       and athlete.family_id = v_invite.family_id
       and athlete.role in ('athlete', 'private_client')
  ) then
    return 'linked';
  end if;
  return 'pending';
end;
$$;

revoke all on function add_athlete_to_family(text) from public, anon;
grant execute on function add_athlete_to_family(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Runners waiting to be set up.
-- ---------------------------------------------------------------------------

-- The runners in this parent's families who have no account yet, with the
-- name the coach issued the codes under. Read through here because parents
-- cannot read invite_codes, and this returns nothing but their own runners'
-- names.
create or replace function my_runners_to_set_up()
returns table (family_id uuid, runner_name text)
language sql stable security definer set search_path = public as $$
  select athlete.family_id, athlete.full_name
    from invite_codes athlete
    join invite_codes mine
      on mine.family_id = athlete.family_id
     and mine.role = 'parent'
     and mine.redeemed_by = auth.uid()
   where athlete.role in ('athlete', 'private_client')
     and athlete.redeemed_at is null
     and (athlete.expires_at is null or athlete.expires_at >= now())
   order by athlete.full_name;
$$;

revoke all on function my_runners_to_set_up() from public, anon;
grant execute on function my_runners_to_set_up() to authenticated;

-- ---------------------------------------------------------------------------
-- Setting up a runner without a phone.
-- ---------------------------------------------------------------------------

create or replace function set_up_runner(p_family uuid, p_name text)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_invite invite_codes%rowtype;
  v_name text := btrim(coalesce(p_name, ''));
  v_athlete uuid;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  if not exists (select 1 from profiles where id = auth.uid() and role = 'parent') then
    raise exception 'Only a parent account can set up a runner';
  end if;

  if v_name = '' then
    raise exception 'Enter your runner''s name';
  end if;
  if char_length(v_name) > 80 then
    raise exception 'That name is too long';
  end if;

  if not exists (
    select 1 from invite_codes mine
     where mine.family_id = p_family
       and mine.role = 'parent'
       and mine.redeemed_by = auth.uid()
  ) then
    raise exception 'That runner is not in your family';
  end if;

  -- The family's athlete code is what makes this a clinic runner, and spending
  -- it means the same runner cannot also be set up a second time, by this
  -- parent or by the code itself.
  select * into v_invite
    from invite_codes
   where family_id = p_family
     and role in ('athlete', 'private_client')
     and redeemed_at is null
   order by created_at
   limit 1
   for update;

  if not found then
    raise exception 'Your runner already has an account. If they have a phone, they signed in with their own code';
  end if;
  if v_invite.expires_at is not null and v_invite.expires_at < now() then
    raise exception 'Your runner''s code has expired. Ask the clinic for a new one';
  end if;

  -- An account nobody signs in to: no email, no password, no identity. It
  -- exists so the runner's training, schedule and profile have an owner.
  -- The empty strings stand in for token columns Supabase's auth server
  -- reads as text and rejects as NULL.
  v_athlete := gen_random_uuid();
  insert into auth.users (
    id, instance_id, aud, role, raw_app_meta_data, raw_user_meta_data,
    confirmation_token, recovery_token, email_change_token_new, email_change,
    created_at, updated_at
  ) values (
    v_athlete, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
    jsonb_build_object('provider', 'managed', 'providers', jsonb_build_array()),
    jsonb_build_object('managed_by', auth.uid()),
    '', '', '', '',
    now(), now()
  );

  insert into profiles (id, full_name, role, managed)
  values (v_athlete, v_name, v_invite.role, true);

  update invite_codes
     set redeemed_by = v_athlete, redeemed_at = now()
   where id = v_invite.id;

  insert into guardian_links (athlete_id, guardian_id)
  select v_athlete, parent.redeemed_by
    from invite_codes parent
   where parent.family_id = p_family
     and parent.role = 'parent'
     and parent.redeemed_by is not null
  on conflict (athlete_id, guardian_id) do nothing;

  insert into audit_log (actor_id, action, table_name, record_id, metadata)
  values (auth.uid(), 'set_up_runner', 'profiles', v_athlete,
          jsonb_build_object('family_id', p_family));

  return v_athlete;
end;
$$;

revoke all on function set_up_runner(uuid, text) from public, anon;
grant execute on function set_up_runner(uuid, text) to authenticated;

