#!/usr/bin/env bash
# Concatenates the migrations, in order, into one file that can be pasted into
# the Supabase SQL editor in a single go.
#
#   npm run db:bundle
#
# Committed so it can be copied straight from GitHub into the SQL editor, but
# generated: never edit it by hand. Schema changes go in supabase/migrations/
# as a new numbered file, then re-run this.
set -euo pipefail

out="supabase/bundled-migrations.sql"

{
  echo "-- Jordan XC Clinic — all migrations, in order."
  echo "-- Generated by scripts/bundle-migrations.sh on $(date -u +%Y-%m-%d). Do not edit."
  echo "-- Paste into the Supabase SQL editor and run once, on a new project."
  echo
  for file in supabase/migrations/*.sql; do
    echo "-- ============================================================"
    echo "-- $(basename "$file")"
    echo "-- ============================================================"
    cat "$file"
    echo
  done
} > "$out"

echo "Wrote $out ($(wc -l < "$out") lines, $(ls supabase/migrations/*.sql | wc -l) migrations)"
